### Create New User
POST http://localhost:3000/auth/signup
Content-Type: application/json

{   
    "hobby": "Ternak lele",
    "email": "hesoyam@gmail.com",
    "password": "halo",
    "Halo": "halo content ini gak masuk karena ValidationPipes whitelist=true"
}

### Find a particular user with a given id
GET http://localhost:3000/auth/1

### Find all user with a given email
GET http://localhost:3000/auth?email=lerucco@gmail.com

### Update a user with given id and body
PATCH http://localhost:3000/auth/4
Content-Type: application/json

{
    "email": "hesoyaaaaam@gmail.com",
    "password": "haloaaa",
    "Halo": "Haloooo"
}

### Delete a user with given id
DELETE  http://localhost:3000/auth/3