### List all messages
GET http://localhost:3001/message

### Create a new message
POST http://localhost:3001/message
Content-Type: application/json

{
    "content": "Dependency Injection"
}

### Create a new message but error return
POST http://localhost:3001/message
Content-Type: application/json

{
    "content": 123
}

### Get a particular message
GET http://localhost:3001/message/953
